// Generated by Bisonc++ V6.01.00 on Mon, 09 Dec 2019 14:04:32 +0800

// base/comment

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved__::UNDETERMINED__, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok__
// which is applied. In this errTok__ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved__
    {
        UNDETERMINED__   = -2,
        EOF__            = -1,
        errTok__         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    enum StateTransition
    {
        ACCEPT__   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {325, 1}, // 1: program ->  exp
     {326, 1}, // 2: exp (INT) ->  INT
     {326, 1}, // 3: exp ->  lvalue
     {326, 1}, // 4: exp (NIL) ->  NIL
     {326, 1}, // 5: exp (STRING) ->  STRING
     {326, 4}, // 6: exp (ID) ->  ID LPAREN nonemptyactuals RPAREN
     {326, 3}, // 7: exp (ID) ->  ID LPAREN RPAREN
     {326, 3}, // 8: exp (OR) ->  exp OR exp
     {326, 3}, // 9: exp (AND) ->  exp AND exp
     {326, 2}, // 10: exp (UMINUS) ->  MINUS exp
     {326, 3}, // 11: exp (PLUS) ->  exp PLUS exp
     {326, 3}, // 12: exp (MINUS) ->  exp MINUS exp
     {326, 3}, // 13: exp (DIVIDE) ->  exp DIVIDE exp
     {326, 3}, // 14: exp (TIMES) ->  exp TIMES exp
     {326, 3}, // 15: exp (EQ) ->  exp EQ exp
     {326, 3}, // 16: exp (NEQ) ->  exp NEQ exp
     {326, 3}, // 17: exp (LT) ->  exp LT exp
     {326, 3}, // 18: exp (LE) ->  exp LE exp
     {326, 3}, // 19: exp (GT) ->  exp GT exp
     {326, 3}, // 20: exp (GE) ->  exp GE exp
     {326, 4}, // 21: exp (ID) ->  ID LBRACE rec_nonempty RBRACE
     {326, 3}, // 22: exp (ID) ->  ID LBRACE RBRACE
     {326, 3}, // 23: exp (ASSIGN) ->  lvalue ASSIGN exp
     {326, 6}, // 24: exp (IF) ->  IF exp THEN exp ELSE exp
     {326, 4}, // 25: exp (IF) ->  IF exp THEN exp
     {326, 4}, // 26: exp (WHILE) ->  WHILE exp DO exp
     {326, 8}, // 27: exp (FOR) ->  FOR ID ASSIGN exp TO exp DO exp
     {326, 1}, // 28: exp (BREAK) ->  BREAK
     {326, 5}, // 29: exp (LET) ->  LET decs IN expseq END
     {326, 6}, // 30: exp (ID) ->  ID LBRACK exp RBRACK OF exp
     {326, 3}, // 31: exp (LPAREN) ->  LPAREN exp RPAREN
     {326, 2}, // 32: exp (LPAREN) ->  LPAREN RPAREN
     {326, 3}, // 33: exp (LPAREN) ->  LPAREN expseq RPAREN
     {327, 1}, // 34: expseq ->  sequencing
     {328, 2}, // 35: sequencing ->  exp sequencing_exps
     {329, 0}, // 36: sequencing_exps ->  <empty>
     {329, 3}, // 37: sequencing_exps (SEMICOLON) ->  SEMICOLON exp sequencing_exps
     {330, 3}, // 38: rec_one (ID) ->  ID EQ exp
     {331, 0}, // 39: rec ->  <empty>
     {331, 3}, // 40: rec (COMMA) ->  COMMA rec_one rec
     {332, 2}, // 41: rec_nonempty ->  rec_one rec
     {333, 2}, // 42: nonemptyactuals ->  exp actuals
     {334, 0}, // 43: actuals ->  <empty>
     {334, 3}, // 44: actuals (COMMA) ->  COMMA exp actuals
     {335, 4}, // 45: lvalue (ID) ->  ID LBRACK exp RBRACK
     {335, 3}, // 46: lvalue (DOT) ->  lvalue DOT ID
     {335, 4}, // 47: lvalue (LBRACK) ->  lvalue LBRACK exp RBRACK
     {335, 1}, // 48: lvalue (ID) ->  ID
     {336, 1}, // 49: decs_nonempty_s ->  tydec
     {336, 1}, // 50: decs_nonempty_s ->  vardec
     {336, 1}, // 51: decs_nonempty_s ->  fundec
     {337, 2}, // 52: decs_nonempty ->  decs_nonempty_s decs
     {338, 0}, // 53: decs ->  <empty>
     {338, 1}, // 54: decs ->  decs_nonempty
     {339, 4}, // 55: tydec_one (TYPE) ->  TYPE ID EQ ty
     {340, 2}, // 56: tydec ->  tydec_one tydec
     {340, 1}, // 57: tydec ->  tydec_one
     {341, 1}, // 58: ty (ID) ->  ID
     {341, 3}, // 59: ty (LBRACE) ->  LBRACE tyfields_nonempty RBRACE
     {341, 3}, // 60: ty (ARRAY) ->  ARRAY OF ID
     {342, 3}, // 61: tyfields_nonempty (COMMA) ->  tyfield COMMA tyfields
     {342, 1}, // 62: tyfields_nonempty ->  tyfield
     {343, 3}, // 63: tyfield (ID) ->  ID COLON ID
     {344, 0}, // 64: tyfields ->  <empty>
     {344, 1}, // 65: tyfields ->  tyfields_nonempty
     {345, 1}, // 66: fundec ->  fundec_one
     {345, 2}, // 67: fundec ->  fundec_one fundec
     {346, 7}, // 68: fundec_one (FUNCTION) ->  FUNCTION ID LPAREN tyfields RPAREN EQ exp
     {346, 9}, // 69: fundec_one (FUNCTION) ->  FUNCTION ID LPAREN tyfields RPAREN COLON ID EQ exp
     {347, 4}, // 70: vardec (VAR) ->  VAR ID ASSIGN exp
     {347, 6}, // 71: vardec (VAR) ->  VAR ID COLON ID ASSIGN exp
     {348, 1}, // 72: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 15} },           
    { {       325}, {  1} }, // program
    { {       326}, {  2} }, // exp    
    { {       259}, {  3} }, // INT    
    { {       335}, {  4} }, // lvalue 
    { {       284}, {  5} }, // NIL    
    { {       258}, {  6} }, // STRING 
    { {       257}, {  7} }, // ID     
    { {       321}, {  8} }, // MINUS  
    { {       272}, {  9} }, // IF     
    { {       275}, { 10} }, // WHILE  
    { {       276}, { 11} }, // FOR    
    { {       283}, { 12} }, // BREAK  
    { {       279}, { 13} }, // LET    
    { {       263}, { 14} }, // LPAREN 
    { {         0}, {  0} },           
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {        2} }, 
    { {     EOF__}, { ACCEPT__} }, 
    { {         0}, {        0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, { 13} },          
    { {     312}, { 15} }, // OR    
    { {     313}, { 16} }, // AND   
    { {     320}, { 17} }, // PLUS  
    { {     321}, { 18} }, // MINUS 
    { {     323}, { 19} }, // DIVIDE
    { {     322}, { 20} }, // TIMES 
    { {     314}, { 21} }, // EQ    
    { {     315}, { 22} }, // NEQ   
    { {     316}, { 23} }, // LT    
    { {     318}, { 24} }, // LE    
    { {     317}, { 25} }, // GT    
    { {     319}, { 26} }, // GE    
    { {       0}, { -1} },          
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_4[] =
{
    { { REQ_DEF}, {  4} },          
    { {     270}, { 27} }, // ASSIGN
    { {     269}, { 28} }, // DOT   
    { {     265}, { 29} }, // LBRACK
    { {       0}, { -3} },          
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_7[] =
{
    { { REQ_DEF}, {   4} },          
    { {     263}, {  30} }, // LPAREN
    { {     267}, {  31} }, // LBRACE
    { {     265}, {  32} }, // LBRACK
    { {       0}, { -48} },          
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 33} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 34} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 35} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       257}, { 36} }, // ID
    { {         0}, {  0} },      
};

SR__ s_12[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_13[] =
{
    { { REQ_DEF}, {  12} },                   
    { {     338}, {  37} }, // decs           
    { {     337}, {  38} }, // decs_nonempty  
    { {     336}, {  39} }, // decs_nonempty_s
    { {     340}, {  40} }, // tydec          
    { {     347}, {  41} }, // vardec         
    { {     345}, {  42} }, // fundec         
    { {     339}, {  43} }, // tydec_one      
    { {     286}, {  44} }, // VAR            
    { {     346}, {  45} }, // fundec_one     
    { {     287}, {  46} }, // TYPE           
    { {     285}, {  47} }, // FUNCTION       
    { {       0}, { -53} },                   
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, { 17} },              
    { {       326}, { 48} }, // exp       
    { {       264}, { 49} }, // RPAREN    
    { {       327}, { 50} }, // expseq    
    { {       259}, {  3} }, // INT       
    { {       335}, {  4} }, // lvalue    
    { {       284}, {  5} }, // NIL       
    { {       258}, {  6} }, // STRING    
    { {       257}, {  7} }, // ID        
    { {       321}, {  8} }, // MINUS     
    { {       272}, {  9} }, // IF        
    { {       275}, { 10} }, // WHILE     
    { {       276}, { 11} }, // FOR       
    { {       283}, { 12} }, // BREAK     
    { {       279}, { 13} }, // LET       
    { {       263}, { 14} }, // LPAREN    
    { {       328}, { 51} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 52} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 53} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 54} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 55} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 56} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 57} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 58} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 59} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 60} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 61} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 62} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 63} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 64} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       257}, { 65} }, // ID
    { {         0}, {  0} },      
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 66} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, { 16} },                   
    { {       333}, { 67} }, // nonemptyactuals
    { {       264}, { 68} }, // RPAREN         
    { {       326}, { 69} }, // exp            
    { {       259}, {  3} }, // INT            
    { {       335}, {  4} }, // lvalue         
    { {       284}, {  5} }, // NIL            
    { {       258}, {  6} }, // STRING         
    { {       257}, {  7} }, // ID             
    { {       321}, {  8} }, // MINUS          
    { {       272}, {  9} }, // IF             
    { {       275}, { 10} }, // WHILE          
    { {       276}, { 11} }, // FOR            
    { {       283}, { 12} }, // BREAK          
    { {       279}, { 13} }, // LET            
    { {       263}, { 14} }, // LPAREN         
    { {         0}, {  0} },                   
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  5} },                
    { {       332}, { 70} }, // rec_nonempty
    { {       268}, { 71} }, // RBRACE      
    { {       330}, { 72} }, // rec_one     
    { {       257}, { 73} }, // ID          
    { {         0}, {  0} },                
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 74} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_33[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       273}, { 75} }, // THEN  
    { {       312}, { 15} }, // OR    
    { {       313}, { 16} }, // AND   
    { {       320}, { 17} }, // PLUS  
    { {       321}, { 18} }, // MINUS 
    { {       323}, { 19} }, // DIVIDE
    { {       322}, { 20} }, // TIMES 
    { {       314}, { 21} }, // EQ    
    { {       315}, { 22} }, // NEQ   
    { {       316}, { 23} }, // LT    
    { {       318}, { 24} }, // LE    
    { {       317}, { 25} }, // GT    
    { {       319}, { 26} }, // GE    
    { {         0}, {  0} },          
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       278}, { 76} }, // DO    
    { {       312}, { 15} }, // OR    
    { {       313}, { 16} }, // AND   
    { {       320}, { 17} }, // PLUS  
    { {       321}, { 18} }, // MINUS 
    { {       323}, { 19} }, // DIVIDE
    { {       322}, { 20} }, // TIMES 
    { {       314}, { 21} }, // EQ    
    { {       315}, { 22} }, // NEQ   
    { {       316}, { 23} }, // LT    
    { {       318}, { 24} }, // LE    
    { {       317}, { 25} }, // GT    
    { {       319}, { 26} }, // GE    
    { {         0}, {  0} },          
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       270}, { 77} }, // ASSIGN
    { {         0}, {  0} },          
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       280}, { 78} }, // IN
    { {         0}, {  0} },      
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_39[] =
{
    { { REQ_DEF}, {  12} },                   
    { {     338}, {  79} }, // decs           
    { {     337}, {  38} }, // decs_nonempty  
    { {     336}, {  39} }, // decs_nonempty_s
    { {     340}, {  40} }, // tydec          
    { {     347}, {  41} }, // vardec         
    { {     345}, {  42} }, // fundec         
    { {     339}, {  43} }, // tydec_one      
    { {     286}, {  44} }, // VAR            
    { {     346}, {  45} }, // fundec_one     
    { {     287}, {  46} }, // TYPE           
    { {     285}, {  47} }, // FUNCTION       
    { {       0}, { -53} },                   
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_43[] =
{
    { { REQ_DEF}, {   4} },             
    { {     340}, {  80} }, // tydec    
    { {     339}, {  43} }, // tydec_one
    { {     287}, {  46} }, // TYPE     
    { {       0}, { -57} },             
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       257}, { 81} }, // ID
    { {         0}, {  0} },      
};

SR__ s_45[] =
{
    { { REQ_DEF}, {   4} },              
    { {     345}, {  82} }, // fundec    
    { {     346}, {  45} }, // fundec_one
    { {     285}, {  47} }, // FUNCTION  
    { {       0}, { -66} },              
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       257}, { 83} }, // ID
    { {         0}, {  0} },      
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       257}, { 84} }, // ID
    { {         0}, {  0} },      
};

SR__ s_48[] =
{
    { { REQ_DEF}, {  16} },                   
    { {     264}, {  85} }, // RPAREN         
    { {     312}, {  15} }, // OR             
    { {     313}, {  16} }, // AND            
    { {     320}, {  17} }, // PLUS           
    { {     321}, {  18} }, // MINUS          
    { {     323}, {  19} }, // DIVIDE         
    { {     322}, {  20} }, // TIMES          
    { {     314}, {  21} }, // EQ             
    { {     315}, {  22} }, // NEQ            
    { {     316}, {  23} }, // LT             
    { {     318}, {  24} }, // LE             
    { {     317}, {  25} }, // GT             
    { {     319}, {  26} }, // GE             
    { {     329}, {  86} }, // sequencing_exps
    { {     262}, {  87} }, // SEMICOLON      
    { {       0}, { -36} },                   
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       264}, { 88} }, // RPAREN
    { {         0}, {  0} },          
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_52[] =
{
    { { REQ_DEF}, { 12} },          
    { {     313}, { 16} }, // AND   
    { {     320}, { 17} }, // PLUS  
    { {     321}, { 18} }, // MINUS 
    { {     323}, { 19} }, // DIVIDE
    { {     322}, { 20} }, // TIMES 
    { {     314}, { 21} }, // EQ    
    { {     315}, { 22} }, // NEQ   
    { {     316}, { 23} }, // LT    
    { {     318}, { 24} }, // LE    
    { {     317}, { 25} }, // GT    
    { {     319}, { 26} }, // GE    
    { {       0}, { -8} },          
};

SR__ s_53[] =
{
    { { REQ_DEF}, { 11} },          
    { {     320}, { 17} }, // PLUS  
    { {     321}, { 18} }, // MINUS 
    { {     323}, { 19} }, // DIVIDE
    { {     322}, { 20} }, // TIMES 
    { {     314}, { 21} }, // EQ    
    { {     315}, { 22} }, // NEQ   
    { {     316}, { 23} }, // LT    
    { {     318}, { 24} }, // LE    
    { {     317}, { 25} }, // GT    
    { {     319}, { 26} }, // GE    
    { {       0}, { -9} },          
};

SR__ s_54[] =
{
    { { REQ_DEF}, {   3} },          
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {       0}, { -11} },          
};

SR__ s_55[] =
{
    { { REQ_DEF}, {   3} },          
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {       0}, { -12} },          
};

SR__ s_56[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_57[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_58[] =
{
    { { REQ_DEF}, {   5} },          
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {       0}, { -15} },          
};

SR__ s_59[] =
{
    { { REQ_DEF}, {   5} },          
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {       0}, { -16} },          
};

SR__ s_60[] =
{
    { { REQ_DEF}, {   5} },          
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {       0}, { -17} },          
};

SR__ s_61[] =
{
    { { REQ_DEF}, {   5} },          
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {       0}, { -18} },          
};

SR__ s_62[] =
{
    { { REQ_DEF}, {   5} },          
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {       0}, { -19} },          
};

SR__ s_63[] =
{
    { { REQ_DEF}, {   5} },          
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {       0}, { -20} },          
};

SR__ s_64[] =
{
    { { REQ_DEF}, {  13} },          
    { {     312}, {  15} }, // OR    
    { {     313}, {  16} }, // AND   
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {     314}, {  21} }, // EQ    
    { {     315}, {  22} }, // NEQ   
    { {     316}, {  23} }, // LT    
    { {     318}, {  24} }, // LE    
    { {     317}, {  25} }, // GT    
    { {     319}, {  26} }, // GE    
    { {       0}, { -23} },          
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       266}, { 89} }, // RBRACK
    { {       312}, { 15} }, // OR    
    { {       313}, { 16} }, // AND   
    { {       320}, { 17} }, // PLUS  
    { {       321}, { 18} }, // MINUS 
    { {       323}, { 19} }, // DIVIDE
    { {       322}, { 20} }, // TIMES 
    { {       314}, { 21} }, // EQ    
    { {       315}, { 22} }, // NEQ   
    { {       316}, { 23} }, // LT    
    { {       318}, { 24} }, // LE    
    { {       317}, { 25} }, // GT    
    { {       319}, { 26} }, // GE    
    { {         0}, {  0} },          
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       264}, { 90} }, // RPAREN
    { {         0}, {  0} },          
};

SR__ s_68[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_69[] =
{
    { { REQ_DEF}, {  15} },           
    { {     334}, {  91} }, // actuals
    { {     312}, {  15} }, // OR     
    { {     313}, {  16} }, // AND    
    { {     320}, {  17} }, // PLUS   
    { {     321}, {  18} }, // MINUS  
    { {     323}, {  19} }, // DIVIDE 
    { {     322}, {  20} }, // TIMES  
    { {     314}, {  21} }, // EQ     
    { {     315}, {  22} }, // NEQ    
    { {     316}, {  23} }, // LT     
    { {     318}, {  24} }, // LE     
    { {     317}, {  25} }, // GT     
    { {     319}, {  26} }, // GE     
    { {     260}, {  92} }, // COMMA  
    { {       0}, { -43} },           
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       268}, { 93} }, // RBRACE
    { {         0}, {  0} },          
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_72[] =
{
    { { REQ_DEF}, {   3} },         
    { {     331}, {  94} }, // rec  
    { {     260}, {  95} }, // COMMA
    { {       0}, { -39} },         
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       314}, { 96} }, // EQ
    { {         0}, {  0} },      
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       266}, { 97} }, // RBRACK
    { {       312}, { 15} }, // OR    
    { {       313}, { 16} }, // AND   
    { {       320}, { 17} }, // PLUS  
    { {       321}, { 18} }, // MINUS 
    { {       323}, { 19} }, // DIVIDE
    { {       322}, { 20} }, // TIMES 
    { {       314}, { 21} }, // EQ    
    { {       315}, { 22} }, // NEQ   
    { {       316}, { 23} }, // LT    
    { {       318}, { 24} }, // LE    
    { {       317}, { 25} }, // GT    
    { {       319}, { 26} }, // GE    
    { {         0}, {  0} },          
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 98} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       326}, { 99} }, // exp   
    { {       259}, {  3} }, // INT   
    { {       335}, {  4} }, // lvalue
    { {       284}, {  5} }, // NIL   
    { {       258}, {  6} }, // STRING
    { {       257}, {  7} }, // ID    
    { {       321}, {  8} }, // MINUS 
    { {       272}, {  9} }, // IF    
    { {       275}, { 10} }, // WHILE 
    { {       276}, { 11} }, // FOR   
    { {       283}, { 12} }, // BREAK 
    { {       279}, { 13} }, // LET   
    { {       263}, { 14} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       326}, { 100} }, // exp   
    { {       259}, {   3} }, // INT   
    { {       335}, {   4} }, // lvalue
    { {       284}, {   5} }, // NIL   
    { {       258}, {   6} }, // STRING
    { {       257}, {   7} }, // ID    
    { {       321}, {   8} }, // MINUS 
    { {       272}, {   9} }, // IF    
    { {       275}, {  10} }, // WHILE 
    { {       276}, {  11} }, // FOR   
    { {       283}, {  12} }, // BREAK 
    { {       279}, {  13} }, // LET   
    { {       263}, {  14} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  16} },              
    { {       327}, { 101} }, // expseq    
    { {       328}, {  51} }, // sequencing
    { {       326}, { 102} }, // exp       
    { {       259}, {   3} }, // INT       
    { {       335}, {   4} }, // lvalue    
    { {       284}, {   5} }, // NIL       
    { {       258}, {   6} }, // STRING    
    { {       257}, {   7} }, // ID        
    { {       321}, {   8} }, // MINUS     
    { {       272}, {   9} }, // IF        
    { {       275}, {  10} }, // WHILE     
    { {       276}, {  11} }, // FOR       
    { {       283}, {  12} }, // BREAK     
    { {       279}, {  13} }, // LET       
    { {       263}, {  14} }, // LPAREN    
    { {         0}, {   0} },              
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {   3} },          
    { {       270}, { 103} }, // ASSIGN
    { {       261}, { 104} }, // COLON 
    { {         0}, {   0} },          
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       314}, { 105} }, // EQ
    { {         0}, {   0} },      
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       263}, { 106} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       326}, { 107} }, // exp   
    { {       259}, {   3} }, // INT   
    { {       335}, {   4} }, // lvalue
    { {       284}, {   5} }, // NIL   
    { {       258}, {   6} }, // STRING
    { {       257}, {   7} }, // ID    
    { {       321}, {   8} }, // MINUS 
    { {       272}, {   9} }, // IF    
    { {       275}, {  10} }, // WHILE 
    { {       276}, {  11} }, // FOR   
    { {       283}, {  12} }, // BREAK 
    { {       279}, {  13} }, // LET   
    { {       263}, {  14} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_90[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       326}, { 108} }, // exp   
    { {       259}, {   3} }, // INT   
    { {       335}, {   4} }, // lvalue
    { {       284}, {   5} }, // NIL   
    { {       258}, {   6} }, // STRING
    { {       257}, {   7} }, // ID    
    { {       321}, {   8} }, // MINUS 
    { {       272}, {   9} }, // IF    
    { {       275}, {  10} }, // WHILE 
    { {       276}, {  11} }, // FOR   
    { {       283}, {  12} }, // BREAK 
    { {       279}, {  13} }, // LET   
    { {       263}, {  14} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_94[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       330}, { 109} }, // rec_one
    { {       257}, {  73} }, // ID     
    { {         0}, {   0} },           
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       326}, { 110} }, // exp   
    { {       259}, {   3} }, // INT   
    { {       335}, {   4} }, // lvalue
    { {       284}, {   5} }, // NIL   
    { {       258}, {   6} }, // STRING
    { {       257}, {   7} }, // ID    
    { {       321}, {   8} }, // MINUS 
    { {       272}, {   9} }, // IF    
    { {       275}, {  10} }, // WHILE 
    { {       276}, {  11} }, // FOR   
    { {       283}, {  12} }, // BREAK 
    { {       279}, {  13} }, // LET   
    { {       263}, {  14} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_97[] =
{
    { { REQ_DEF}, {   2} },      
    { {     282}, { 111} }, // OF
    { {       0}, { -45} },      
};

SR__ s_98[] =
{
    { { REQ_DEF}, {  14} },          
    { {     274}, { 112} }, // ELSE  
    { {     312}, {  15} }, // OR    
    { {     313}, {  16} }, // AND   
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {     314}, {  21} }, // EQ    
    { {     315}, {  22} }, // NEQ   
    { {     316}, {  23} }, // LT    
    { {     318}, {  24} }, // LE    
    { {     317}, {  25} }, // GT    
    { {     319}, {  26} }, // GE    
    { {       0}, { -25} },          
};

SR__ s_99[] =
{
    { { REQ_DEF}, {  13} },          
    { {     312}, {  15} }, // OR    
    { {     313}, {  16} }, // AND   
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {     314}, {  21} }, // EQ    
    { {     315}, {  22} }, // NEQ   
    { {     316}, {  23} }, // LT    
    { {     318}, {  24} }, // LE    
    { {     317}, {  25} }, // GT    
    { {     319}, {  26} }, // GE    
    { {       0}, { -26} },          
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       277}, { 113} }, // TO    
    { {       312}, {  15} }, // OR    
    { {       313}, {  16} }, // AND   
    { {       320}, {  17} }, // PLUS  
    { {       321}, {  18} }, // MINUS 
    { {       323}, {  19} }, // DIVIDE
    { {       322}, {  20} }, // TIMES 
    { {       314}, {  21} }, // EQ    
    { {       315}, {  22} }, // NEQ   
    { {       316}, {  23} }, // LT    
    { {       318}, {  24} }, // LE    
    { {       317}, {  25} }, // GT    
    { {       319}, {  26} }, // GE    
    { {         0}, {   0} },          
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       281}, { 114} }, // END
    { {         0}, {   0} },       
};

SR__ s_102[] =
{
    { { REQ_DEF}, {  15} },                   
    { {     329}, {  86} }, // sequencing_exps
    { {     312}, {  15} }, // OR             
    { {     313}, {  16} }, // AND            
    { {     320}, {  17} }, // PLUS           
    { {     321}, {  18} }, // MINUS          
    { {     323}, {  19} }, // DIVIDE         
    { {     322}, {  20} }, // TIMES          
    { {     314}, {  21} }, // EQ             
    { {     315}, {  22} }, // NEQ            
    { {     316}, {  23} }, // LT             
    { {     318}, {  24} }, // LE             
    { {     317}, {  25} }, // GT             
    { {     319}, {  26} }, // GE             
    { {     262}, {  87} }, // SEMICOLON      
    { {       0}, { -36} },                   
};

SR__ s_103[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       326}, { 115} }, // exp   
    { {       259}, {   3} }, // INT   
    { {       335}, {   4} }, // lvalue
    { {       284}, {   5} }, // NIL   
    { {       258}, {   6} }, // STRING
    { {       257}, {   7} }, // ID    
    { {       321}, {   8} }, // MINUS 
    { {       272}, {   9} }, // IF    
    { {       275}, {  10} }, // WHILE 
    { {       276}, {  11} }, // FOR   
    { {       283}, {  12} }, // BREAK 
    { {       279}, {  13} }, // LET   
    { {       263}, {  14} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       257}, { 116} }, // ID
    { {         0}, {   0} },      
};

SR__ s_105[] =
{
    { { REQ_TOKEN}, {   5} },          
    { {       341}, { 117} }, // ty    
    { {       257}, { 118} }, // ID    
    { {       267}, { 119} }, // LBRACE
    { {       271}, { 120} }, // ARRAY 
    { {         0}, {   0} },          
};

SR__ s_106[] =
{
    { { REQ_DEF}, {   5} },                     
    { {     344}, { 121} }, // tyfields         
    { {     342}, { 122} }, // tyfields_nonempty
    { {     343}, { 123} }, // tyfield          
    { {     257}, { 124} }, // ID               
    { {       0}, { -64} },                     
};

SR__ s_107[] =
{
    { { REQ_DEF}, {  15} },                   
    { {     329}, { 125} }, // sequencing_exps
    { {     312}, {  15} }, // OR             
    { {     313}, {  16} }, // AND            
    { {     320}, {  17} }, // PLUS           
    { {     321}, {  18} }, // MINUS          
    { {     323}, {  19} }, // DIVIDE         
    { {     322}, {  20} }, // TIMES          
    { {     314}, {  21} }, // EQ             
    { {     315}, {  22} }, // NEQ            
    { {     316}, {  23} }, // LT             
    { {     318}, {  24} }, // LE             
    { {     317}, {  25} }, // GT             
    { {     319}, {  26} }, // GE             
    { {     262}, {  87} }, // SEMICOLON      
    { {       0}, { -36} },                   
};

SR__ s_108[] =
{
    { { REQ_DEF}, {  15} },           
    { {     334}, { 126} }, // actuals
    { {     312}, {  15} }, // OR     
    { {     313}, {  16} }, // AND    
    { {     320}, {  17} }, // PLUS   
    { {     321}, {  18} }, // MINUS  
    { {     323}, {  19} }, // DIVIDE 
    { {     322}, {  20} }, // TIMES  
    { {     314}, {  21} }, // EQ     
    { {     315}, {  22} }, // NEQ    
    { {     316}, {  23} }, // LT     
    { {     318}, {  24} }, // LE     
    { {     317}, {  25} }, // GT     
    { {     319}, {  26} }, // GE     
    { {     260}, {  92} }, // COMMA  
    { {       0}, { -43} },           
};

SR__ s_109[] =
{
    { { REQ_DEF}, {   3} },         
    { {     331}, { 127} }, // rec  
    { {     260}, {  95} }, // COMMA
    { {       0}, { -39} },         
};

SR__ s_110[] =
{
    { { REQ_DEF}, {  13} },          
    { {     312}, {  15} }, // OR    
    { {     313}, {  16} }, // AND   
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {     314}, {  21} }, // EQ    
    { {     315}, {  22} }, // NEQ   
    { {     316}, {  23} }, // LT    
    { {     318}, {  24} }, // LE    
    { {     317}, {  25} }, // GT    
    { {     319}, {  26} }, // GE    
    { {       0}, { -38} },          
};

SR__ s_111[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       326}, { 128} }, // exp   
    { {       259}, {   3} }, // INT   
    { {       335}, {   4} }, // lvalue
    { {       284}, {   5} }, // NIL   
    { {       258}, {   6} }, // STRING
    { {       257}, {   7} }, // ID    
    { {       321}, {   8} }, // MINUS 
    { {       272}, {   9} }, // IF    
    { {       275}, {  10} }, // WHILE 
    { {       276}, {  11} }, // FOR   
    { {       283}, {  12} }, // BREAK 
    { {       279}, {  13} }, // LET   
    { {       263}, {  14} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_112[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       326}, { 129} }, // exp   
    { {       259}, {   3} }, // INT   
    { {       335}, {   4} }, // lvalue
    { {       284}, {   5} }, // NIL   
    { {       258}, {   6} }, // STRING
    { {       257}, {   7} }, // ID    
    { {       321}, {   8} }, // MINUS 
    { {       272}, {   9} }, // IF    
    { {       275}, {  10} }, // WHILE 
    { {       276}, {  11} }, // FOR   
    { {       283}, {  12} }, // BREAK 
    { {       279}, {  13} }, // LET   
    { {       263}, {  14} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       326}, { 130} }, // exp   
    { {       259}, {   3} }, // INT   
    { {       335}, {   4} }, // lvalue
    { {       284}, {   5} }, // NIL   
    { {       258}, {   6} }, // STRING
    { {       257}, {   7} }, // ID    
    { {       321}, {   8} }, // MINUS 
    { {       272}, {   9} }, // IF    
    { {       275}, {  10} }, // WHILE 
    { {       276}, {  11} }, // FOR   
    { {       283}, {  12} }, // BREAK 
    { {       279}, {  13} }, // LET   
    { {       263}, {  14} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_114[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_115[] =
{
    { { REQ_DEF}, {  13} },          
    { {     312}, {  15} }, // OR    
    { {     313}, {  16} }, // AND   
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {     314}, {  21} }, // EQ    
    { {     315}, {  22} }, // NEQ   
    { {     316}, {  23} }, // LT    
    { {     318}, {  24} }, // LE    
    { {     317}, {  25} }, // GT    
    { {     319}, {  26} }, // GE    
    { {       0}, { -70} },          
};

SR__ s_116[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       270}, { 131} }, // ASSIGN
    { {         0}, {   0} },          
};

SR__ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_118[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_119[] =
{
    { { REQ_TOKEN}, {   4} },                     
    { {       342}, { 132} }, // tyfields_nonempty
    { {       343}, { 123} }, // tyfield          
    { {       257}, { 124} }, // ID               
    { {         0}, {   0} },                     
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       282}, { 133} }, // OF
    { {         0}, {   0} },      
};

SR__ s_121[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       264}, { 134} }, // RPAREN
    { {         0}, {   0} },          
};

SR__ s_122[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_123[] =
{
    { { REQ_DEF}, {   2} },         
    { {     260}, { 135} }, // COMMA
    { {       0}, { -62} },         
};

SR__ s_124[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       261}, { 136} }, // COLON
    { {         0}, {   0} },         
};

SR__ s_125[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_126[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_127[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_128[] =
{
    { { REQ_DEF}, {  13} },          
    { {     312}, {  15} }, // OR    
    { {     313}, {  16} }, // AND   
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {     314}, {  21} }, // EQ    
    { {     315}, {  22} }, // NEQ   
    { {     316}, {  23} }, // LT    
    { {     318}, {  24} }, // LE    
    { {     317}, {  25} }, // GT    
    { {     319}, {  26} }, // GE    
    { {       0}, { -30} },          
};

SR__ s_129[] =
{
    { { REQ_DEF}, {  13} },          
    { {     312}, {  15} }, // OR    
    { {     313}, {  16} }, // AND   
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {     314}, {  21} }, // EQ    
    { {     315}, {  22} }, // NEQ   
    { {     316}, {  23} }, // LT    
    { {     318}, {  24} }, // LE    
    { {     317}, {  25} }, // GT    
    { {     319}, {  26} }, // GE    
    { {       0}, { -24} },          
};

SR__ s_130[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       278}, { 137} }, // DO    
    { {       312}, {  15} }, // OR    
    { {       313}, {  16} }, // AND   
    { {       320}, {  17} }, // PLUS  
    { {       321}, {  18} }, // MINUS 
    { {       323}, {  19} }, // DIVIDE
    { {       322}, {  20} }, // TIMES 
    { {       314}, {  21} }, // EQ    
    { {       315}, {  22} }, // NEQ   
    { {       316}, {  23} }, // LT    
    { {       318}, {  24} }, // LE    
    { {       317}, {  25} }, // GT    
    { {       319}, {  26} }, // GE    
    { {         0}, {   0} },          
};

SR__ s_131[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       326}, { 138} }, // exp   
    { {       259}, {   3} }, // INT   
    { {       335}, {   4} }, // lvalue
    { {       284}, {   5} }, // NIL   
    { {       258}, {   6} }, // STRING
    { {       257}, {   7} }, // ID    
    { {       321}, {   8} }, // MINUS 
    { {       272}, {   9} }, // IF    
    { {       275}, {  10} }, // WHILE 
    { {       276}, {  11} }, // FOR   
    { {       283}, {  12} }, // BREAK 
    { {       279}, {  13} }, // LET   
    { {       263}, {  14} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_132[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       268}, { 139} }, // RBRACE
    { {         0}, {   0} },          
};

SR__ s_133[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       257}, { 140} }, // ID
    { {         0}, {   0} },      
};

SR__ s_134[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {       314}, { 141} }, // EQ   
    { {       261}, { 142} }, // COLON
    { {         0}, {   0} },         
};

SR__ s_135[] =
{
    { { REQ_DEF}, {   5} },                     
    { {     344}, { 143} }, // tyfields         
    { {     342}, { 122} }, // tyfields_nonempty
    { {     343}, { 123} }, // tyfield          
    { {     257}, { 124} }, // ID               
    { {       0}, { -64} },                     
};

SR__ s_136[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       257}, { 144} }, // ID
    { {         0}, {   0} },      
};

SR__ s_137[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       326}, { 145} }, // exp   
    { {       259}, {   3} }, // INT   
    { {       335}, {   4} }, // lvalue
    { {       284}, {   5} }, // NIL   
    { {       258}, {   6} }, // STRING
    { {       257}, {   7} }, // ID    
    { {       321}, {   8} }, // MINUS 
    { {       272}, {   9} }, // IF    
    { {       275}, {  10} }, // WHILE 
    { {       276}, {  11} }, // FOR   
    { {       283}, {  12} }, // BREAK 
    { {       279}, {  13} }, // LET   
    { {       263}, {  14} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_138[] =
{
    { { REQ_DEF}, {  13} },          
    { {     312}, {  15} }, // OR    
    { {     313}, {  16} }, // AND   
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {     314}, {  21} }, // EQ    
    { {     315}, {  22} }, // NEQ   
    { {     316}, {  23} }, // LT    
    { {     318}, {  24} }, // LE    
    { {     317}, {  25} }, // GT    
    { {     319}, {  26} }, // GE    
    { {       0}, { -71} },          
};

SR__ s_139[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_140[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_141[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       326}, { 146} }, // exp   
    { {       259}, {   3} }, // INT   
    { {       335}, {   4} }, // lvalue
    { {       284}, {   5} }, // NIL   
    { {       258}, {   6} }, // STRING
    { {       257}, {   7} }, // ID    
    { {       321}, {   8} }, // MINUS 
    { {       272}, {   9} }, // IF    
    { {       275}, {  10} }, // WHILE 
    { {       276}, {  11} }, // FOR   
    { {       283}, {  12} }, // BREAK 
    { {       279}, {  13} }, // LET   
    { {       263}, {  14} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_142[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       257}, { 147} }, // ID
    { {         0}, {   0} },      
};

SR__ s_143[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_144[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_145[] =
{
    { { REQ_DEF}, {  13} },          
    { {     312}, {  15} }, // OR    
    { {     313}, {  16} }, // AND   
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {     314}, {  21} }, // EQ    
    { {     315}, {  22} }, // NEQ   
    { {     316}, {  23} }, // LT    
    { {     318}, {  24} }, // LE    
    { {     317}, {  25} }, // GT    
    { {     319}, {  26} }, // GE    
    { {       0}, { -27} },          
};

SR__ s_146[] =
{
    { { REQ_DEF}, {  13} },          
    { {     312}, {  15} }, // OR    
    { {     313}, {  16} }, // AND   
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {     314}, {  21} }, // EQ    
    { {     315}, {  22} }, // NEQ   
    { {     316}, {  23} }, // LT    
    { {     318}, {  24} }, // LE    
    { {     317}, {  25} }, // GT    
    { {     319}, {  26} }, // GE    
    { {       0}, { -68} },          
};

SR__ s_147[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       314}, { 148} }, // EQ
    { {         0}, {   0} },      
};

SR__ s_148[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       326}, { 149} }, // exp   
    { {       259}, {   3} }, // INT   
    { {       335}, {   4} }, // lvalue
    { {       284}, {   5} }, // NIL   
    { {       258}, {   6} }, // STRING
    { {       257}, {   7} }, // ID    
    { {       321}, {   8} }, // MINUS 
    { {       272}, {   9} }, // IF    
    { {       275}, {  10} }, // WHILE 
    { {       276}, {  11} }, // FOR   
    { {       283}, {  12} }, // BREAK 
    { {       279}, {  13} }, // LET   
    { {       263}, {  14} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_149[] =
{
    { { REQ_DEF}, {  13} },          
    { {     312}, {  15} }, // OR    
    { {     313}, {  16} }, // AND   
    { {     320}, {  17} }, // PLUS  
    { {     321}, {  18} }, // MINUS 
    { {     323}, {  19} }, // DIVIDE
    { {     322}, {  20} }, // TIMES 
    { {     314}, {  21} }, // EQ    
    { {     315}, {  22} }, // NEQ   
    { {     316}, {  23} }, // LT    
    { {     318}, {  24} }, // LE    
    { {     317}, {  25} }, // GT    
    { {     319}, {  26} }, // GE    
    { {       0}, { -69} },          
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
};

} // anonymous namespace ends




// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
ParserBase::ParserBase()
:
    d_token(Reserved__::UNDETERMINED__),
    // $insert baseclasscode
    d_requiredTokens__(0)
{
}

// base/clearin
void ParserBase::clearin__()
{
    d_nErrors__ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    d_token = Reserved__::UNDETERMINED__;
    d_next = TokenPair{ Reserved__::UNDETERMINED__, STYPE__{} };
    d_recovery = false;
    d_acceptedTokens__ = d_requiredTokens__;
    d_val__ = STYPE__{};

    push__(0);
}

// base/debugfunctions

void ParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void ParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

// base/lex
void ParserBase::lex__(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved__::EOF__;

    d_terminalToken = true;
}

// base/lookup
int ParserBase::lookup__() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR__ const *sr = s_state[d_state];
    SR__ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;


    return action;
}

// base/pop
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

}

// base/poptoken
void ParserBase::popToken__()
{
    d_token = d_next.first;
    d_val__ = std::move(d_next.second);

    d_next.first = Reserved__::UNDETERMINED__;
}

// base/push
void ParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize__() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack.resize(newSize);
    }

    ++d_stackIdx;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val__) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    }
    else
    {
    }
}

// base/pushtoken
void ParserBase::pushToken__(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val__) };
    d_token = token;
}

// base/redotoken
void ParserBase::redoToken__()
{
    if (d_token != Reserved__::UNDETERMINED__)
        pushToken__(d_token);
}

// base/reduce
void ParserBase::reduce__(int rule)
{
    PI__ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    pop__(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void ParserBase::shift__(int action)
{
    push__(action);
    popToken__();               // token processed

    if (d_recovery and d_terminalToken)
    {
        d_recovery = false;
        d_acceptedTokens__ = 0;
    }
}

// base/startrecovery
void ParserBase::startRecovery__()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken__(Reserved__::errTok__);      // specify errTok__ as next token
    push__(lookup__());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t ParserBase::top__() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void Parser::errorRecovery__()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)



    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle__ for details.

    startRecovery__();
}

// derived/executeaction
void Parser::executeAction__(int production)
try
{
    if (token__() != Reserved__::UNDETERMINED__)
        pushToken__(token__());     // save an already available token
    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 71 "tiger.y"
        {absyn_root = vs__(0).exp;}
        break;

        case 2:
#line 73 "tiger.y"
        {d_val__.exp = new A::IntExp(errormsg.tokPos, vs__(0).ival);}
        break;

        case 3:
#line 74 "tiger.y"
        {d_val__.exp = new A::VarExp(errormsg.tokPos, vs__(0).var);}
        break;

        case 4:
#line 75 "tiger.y"
        {d_val__.exp = new A::NilExp(errormsg.tokPos);}
        break;

        case 5:
#line 76 "tiger.y"
        {d_val__.exp = new A::StringExp(errormsg.tokPos, vs__(0).sval);}
        break;

        case 6:
#line 77 "tiger.y"
        {d_val__.exp = new A::CallExp(errormsg.tokPos, vs__(-3).sym, vs__(-1).explist);}
        break;

        case 7:
#line 78 "tiger.y"
        {d_val__.exp = new A::CallExp(errormsg.tokPos, vs__(-2).sym, NULL);}
        break;

        case 8:
#line 79 "tiger.y"
        {d_val__.exp = new A::IfExp(errormsg.tokPos, vs__(-2).exp, new A::IntExp(errormsg.tokPos, 1), vs__(0).exp);}
        break;

        case 9:
#line 80 "tiger.y"
        {d_val__.exp = new A::IfExp(errormsg.tokPos, vs__(-2).exp, vs__(0).exp, new A::IntExp(errormsg.tokPos, 0));}
        break;

        case 10:
#line 81 "tiger.y"
        {d_val__.exp = new A::OpExp(errormsg.tokPos, A::MINUS_OP, new A::IntExp(errormsg.tokPos, 0), vs__(0).exp);}
        break;

        case 11:
#line 82 "tiger.y"
        {d_val__.exp = new A::OpExp(errormsg.tokPos, A::PLUS_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 12:
#line 83 "tiger.y"
        {d_val__.exp = new A::OpExp(errormsg.tokPos, A::MINUS_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 13:
#line 84 "tiger.y"
        {d_val__.exp = new A::OpExp(errormsg.tokPos, A::DIVIDE_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 14:
#line 85 "tiger.y"
        {d_val__.exp = new A::OpExp(errormsg.tokPos, A::TIMES_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 15:
#line 86 "tiger.y"
        {d_val__.exp = new A::OpExp(errormsg.tokPos, A::EQ_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 16:
#line 87 "tiger.y"
        {d_val__.exp = new A::OpExp(errormsg.tokPos, A::NEQ_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 17:
#line 88 "tiger.y"
        {d_val__.exp = new A::OpExp(errormsg.tokPos, A::LT_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 18:
#line 89 "tiger.y"
        {d_val__.exp = new A::OpExp(errormsg.tokPos, A::LE_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 19:
#line 90 "tiger.y"
        {d_val__.exp = new A::OpExp(errormsg.tokPos, A::GT_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 20:
#line 91 "tiger.y"
        {d_val__.exp = new A::OpExp(errormsg.tokPos, A::GE_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 21:
#line 92 "tiger.y"
        {d_val__.exp = new A::RecordExp(errormsg.tokPos, vs__(-3).sym, vs__(-1).efieldlist);}
        break;

        case 22:
#line 93 "tiger.y"
        {d_val__.exp = new A::RecordExp(errormsg.tokPos, vs__(-2).sym, NULL);}
        break;

        case 23:
#line 94 "tiger.y"
        {d_val__.exp = new A::AssignExp(errormsg.tokPos, vs__(-2).var, vs__(0).exp);}
        break;

        case 24:
#line 95 "tiger.y"
        {d_val__.exp = new A::IfExp(errormsg.tokPos, vs__(-4).exp, vs__(-2).exp, vs__(0).exp);}
        break;

        case 25:
#line 96 "tiger.y"
        {d_val__.exp = new A::IfExp(errormsg.tokPos, vs__(-2).exp, vs__(0).exp, NULL);}
        break;

        case 26:
#line 97 "tiger.y"
        {d_val__.exp = new A::WhileExp(errormsg.tokPos, vs__(-2).exp, vs__(0).exp);}
        break;

        case 27:
#line 98 "tiger.y"
        {d_val__.exp = new A::ForExp(errormsg.tokPos, vs__(-6).sym, vs__(-4).exp, vs__(-2).exp, vs__(0).exp);}
        break;

        case 28:
#line 99 "tiger.y"
        {d_val__.exp = new A::BreakExp(errormsg.tokPos);}
        break;

        case 29:
#line 100 "tiger.y"
        {d_val__.exp = new A::LetExp(errormsg.tokPos, vs__(-3).declist, vs__(-1).exp);}
        break;

        case 30:
#line 101 "tiger.y"
        {d_val__.exp = new A::ArrayExp(errormsg.tokPos, vs__(-5).sym, vs__(-3).exp, vs__(0).exp);}
        break;

        case 31:
#line 102 "tiger.y"
        {d_val__.exp = vs__(-1).exp;}
        break;

        case 32:
#line 103 "tiger.y"
        {d_val__.exp = new A::VoidExp(errormsg.tokPos);}
        break;

        case 33:
#line 104 "tiger.y"
        {d_val__.exp = vs__(-1).exp;}
        break;

        case 34:
#line 106 "tiger.y"
        {d_val__.exp = new A::SeqExp(errormsg.tokPos, vs__(0).explist);}
        break;

        case 35:
#line 107 "tiger.y"
        {d_val__.explist = new A::ExpList(vs__(-1).exp, vs__(0).explist);}
        break;

        case 36:
#line 108 "tiger.y"
        {d_val__.explist = NULL;}
        break;

        case 37:
#line 109 "tiger.y"
        {d_val__.explist = new A::ExpList(vs__(-1).exp, vs__(0).explist);}
        break;

        case 38:
#line 110 "tiger.y"
        {d_val__.efield = new A::EField(vs__(-2).sym, vs__(0).exp);}
        break;

        case 39:
#line 111 "tiger.y"
        {d_val__.efieldlist = NULL;}
        break;

        case 40:
#line 112 "tiger.y"
        {d_val__.efieldlist = new A::EFieldList(vs__(-1).efield, vs__(0).efieldlist);}
        break;

        case 41:
#line 113 "tiger.y"
        {d_val__.efieldlist = new A::EFieldList(vs__(-1).efield, vs__(0).efieldlist);}
        break;

        case 42:
#line 114 "tiger.y"
        {d_val__.explist = new A::ExpList(vs__(-1).exp, vs__(0).explist);}
        break;

        case 43:
#line 115 "tiger.y"
        {d_val__.explist = NULL;}
        break;

        case 44:
#line 116 "tiger.y"
        {d_val__.explist = new A::ExpList(vs__(-1).exp, vs__(0).explist);}
        break;

        case 45:
#line 118 "tiger.y"
        {d_val__.var = new A::SubscriptVar(errormsg.tokPos, new A::SimpleVar(errormsg.tokPos, vs__(-3).sym), vs__(-1).exp);}
        break;

        case 46:
#line 119 "tiger.y"
        {d_val__.var = new A::FieldVar(errormsg.tokPos, vs__(-2).var, vs__(0).sym);}
        break;

        case 47:
#line 120 "tiger.y"
        {d_val__.var = new A::SubscriptVar(errormsg.tokPos, vs__(-3).var, vs__(-1).exp);}
        break;

        case 48:
#line 121 "tiger.y"
        {d_val__.var = new A::SimpleVar(errormsg.tokPos, vs__(0).sym);}
        break;

        case 49:
#line 123 "tiger.y"
        {d_val__.dec = new A::TypeDec(errormsg.tokPos, vs__(0).tydeclist);}
        break;

        case 50:
#line 124 "tiger.y"
        {d_val__.dec = vs__(0).dec;}
        break;

        case 51:
#line 125 "tiger.y"
        {d_val__.dec = new A::FunctionDec(errormsg.tokPos, vs__(0).fundeclist);}
        break;

        case 52:
#line 126 "tiger.y"
        {d_val__.declist = new A::DecList(vs__(-1).dec, vs__(0).declist);}
        break;

        case 53:
#line 127 "tiger.y"
        {d_val__.declist = NULL;}
        break;

        case 54:
#line 128 "tiger.y"
        {d_val__.declist = vs__(0).declist;}
        break;

        case 55:
#line 130 "tiger.y"
        {d_val__.tydec = new A::NameAndTy(vs__(-2).sym, vs__(0).ty);}
        break;

        case 56:
#line 131 "tiger.y"
        {d_val__.tydeclist = new A::NameAndTyList(vs__(-1).tydec, vs__(0).tydeclist);}
        break;

        case 57:
#line 132 "tiger.y"
        {d_val__.tydeclist = new A::NameAndTyList(vs__(0).tydec, NULL);}
        break;

        case 58:
#line 134 "tiger.y"
        {d_val__.ty = new A::NameTy(errormsg.tokPos, vs__(0).sym);}
        break;

        case 59:
#line 135 "tiger.y"
        {d_val__.ty = new A::RecordTy(errormsg.tokPos, vs__(-1).fieldlist);}
        break;

        case 60:
#line 136 "tiger.y"
        {d_val__.ty = new A::ArrayTy(errormsg.tokPos, vs__(0).sym);}
        break;

        case 61:
#line 138 "tiger.y"
        {d_val__.fieldlist = new A::FieldList(vs__(-2).field, vs__(0).fieldlist);}
        break;

        case 62:
#line 139 "tiger.y"
        {d_val__.fieldlist = new A::FieldList(vs__(0).field, NULL);}
        break;

        case 63:
#line 140 "tiger.y"
        {d_val__.field = new A::Field(errormsg.tokPos, vs__(-2).sym, vs__(0).sym);}
        break;

        case 64:
#line 141 "tiger.y"
        {d_val__.fieldlist = NULL;}
        break;

        case 65:
#line 142 "tiger.y"
        {d_val__.fieldlist = vs__(0).fieldlist;}
        break;

        case 66:
#line 143 "tiger.y"
        {d_val__.fundeclist = new A::FunDecList(vs__(0).fundec, NULL);}
        break;

        case 67:
#line 144 "tiger.y"
        {d_val__.fundeclist = new A::FunDecList(vs__(-1).fundec, vs__(0).fundeclist);}
        break;

        case 68:
#line 146 "tiger.y"
        {d_val__.fundec = new A::FunDec(errormsg.tokPos, vs__(-5).sym, vs__(-3).fieldlist, NULL, vs__(0).exp);}
        break;

        case 69:
#line 147 "tiger.y"
        {d_val__.fundec = new A::FunDec(errormsg.tokPos, vs__(-7).sym, vs__(-5).fieldlist, vs__(-2).sym, vs__(0).exp); }
        break;

        case 70:
#line 149 "tiger.y"
        {d_val__.dec = new A::VarDec(errormsg.tokPos,vs__(-2).sym, nullptr, vs__(0).exp);}
        break;

        case 71:
#line 150 "tiger.y"
        {d_val__.dec = new A::VarDec(errormsg.tokPos, vs__(-4).sym, vs__(-2).sym, vs__(0).exp);}
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void Parser::nextCycle__()
try
{
    if (s_state[state__()]->d_type & REQ_TOKEN)
        nextToken__();              // obtain next token


    int action = lookup__();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift__(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {

        if (recovery__())
            redoToken__();
        else
            executeAction__(-action);
                                            // next token is the rule's LHS
        reduce__(-action); 
        return;
    }

    if (recovery__())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery__)
{
    if (not recovery__())
        errorRecovery__();
    else
    {
        if (token__() == Reserved__::EOF__)
            ABORT();
        popToken__();               // skip the failing token
    }
}


// derived/nexttoken
void Parser::nextToken__()
{ 
    // If d_token is Reserved__::UNDETERMINED__ then if savedToken__() is
    // Reserved__::UNDETERMINED__ another token is obtained from lex(). Then
    // savedToken__() is assigned to d_token.

                                    // no need for a token: got one already
    if (token__() != Reserved__::UNDETERMINED__) 
    {
        return;                             
    }

    if (savedToken__() != Reserved__::UNDETERMINED__)
    {
        popToken__();               // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;       // accept another token (see
                                    // errorRecover())
        lex__(lex());
        print__();
    }
    print();
}

// derived/print
void Parser::print__()
{
// $insert print
}

// derived/parse
int Parser::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin__.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    clearin__();                            // initialize, push(0)

    while (true)
    {
// $insert prompt
        nextCycle__();
    }
}
catch (Return__ retValue)
{
    return retValue or d_nErrors__;
}


// derived/tail


